id = "react-snippets-es7"
name = "ES7+ React/Redux/React-Native snippets for Zed"
version = "0.0.1"
schema_version = 1
authors = ["Shone Binu <hello@shonebinu.com>"]
description = "Converted React/Redux/React-Native snippets from the popular 'ES7+ React/Redux/React-Native snippets' VSCode extension."
repository = "https://github.com/shonebinu/zed-react-snippets"
snippets = "./snippets/tsx.json" # afaik only one snippet can be added
